# License Scanner Config


[environment]

title = "License Scanner Config"

# configure the tool to use.
# currently only fossa is supported
# tool = "fossa"

# How we should process the licenses
# options are: 
# - "fossa-api": will export to fossa api (requires FOSSA_API_KEY to be set in .env)
# - "fossa-json": will export from fossa to a folder of json files
# - "csv": will export to a list of csv files
# tool = "fossa-api"
tool = "csv"