# License Scanner Config

[environment]

title = "License Scanner Config"

# How we should process the licenses
# options are: 
# - "fossa-api": will export to fossa api (requires FOSSA_API_KEY to be set in .env)
# - "fossa-json": will export from fossa to a folder of json files. This just shows imports heirarchies, and doesn't scan licenses
# - "lc-csv": will use npm license-checker, and export to a list of csv files
tool = "lc-csv"


##
# The list of repos to scan
# Lines starting with a # will be ignored
##
repos = [
  "https://github.com/mojaloop/account-lookup-service",
  "https://github.com/mojaloop/central-ledger",
  "https://github.com/mojaloop/quoting-service",
  "https://github.com/mojaloop/central-event-processor",
  "https://github.com/mojaloop/forensic-logging-client",
  "https://github.com/mojaloop/central-end-user-registry",
  "https://github.com/mojaloop/ml-api-adapter",
  "https://github.com/mojaloop/simulator",
  "https://github.com/mojaloop/mock-pathfinder",
  "https://github.com/mojaloop/pathfinder-provisioning-client",
  "https://github.com/mojaloop/central-services-stream",
  "https://github.com/mojaloop/email-notifier",
  "https://github.com/mojaloop/central-settlement",
  "https://github.com/mojaloop/cross-network",
  "https://github.com/mojaloop/als-oracle-template",
  "https://github.com/mojaloop/interop-switch-js",
  "https://github.com/mojaloop/central-services-shared",
  "https://github.com/mojaloop/central-services-error-handling",
  "https://github.com/mojaloop/central-services-auth",
  "https://github.com/mojaloop/central-services-database",
  "https://github.com/mojaloop/central-services-metrics",
  "https://github.com/mojaloop/forensic-logging-sidecar",
  "https://github.com/mojaloop/central-directory",
]